"""
This file serves as the FastAPI backend where users can send questions, 
and the system will return answers generated by the LLM based on the 
relevant document context.
"""
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

class QuestionRequest(BaseModel):
    user_name: str
    question: str

@app.post("/ask")
async def ask_question(request: QuestionRequest):
    return {"response": f"{request.user_name} asked: {request.question}"}